targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/models/api/*.dart
            - lib/network/services/*.dart
            - lib/network/utils/*.dart

        options:
          explicit_to_json: true
          include_if_null: false

