name: doctor_consultation
description: Mobile application for doctor consultation

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.12+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 2.2.0
  cupertino_icons: ^1.0.2
#  Splash Screen Loading
  flutter_spinkit: ^5.1.0
#  For SVG icons or images
  flutter_svg: ^1.0.2
  carousel_slider: ^4.0.0
# Read More HomePage
  readmore: ^2.1.0
#  Expandable Text
  expandable_text: ^2.2.0
#  Dropdown
  dropdown_button2: ^1.1.1

#  For Timeline
  timeline_tile: ^2.0.0

# Sliding 1
  sliding_up_panel: ^2.0.0+1
  cached_network_image: ^3.2.0

#  Sliding 2
  snapping_sheet: ^3.1.0
#  Rating
  flutter_rating_bar: ^4.0.0

#  Circular Chart
  awesome_circular_chart: ^1.0.0
#  Timing
  intl: ^0.17.0

#  Alphabetical Patient
  alphabet_list_scroll_view_fix: ^2.0.2
  alphabet_scroll_view: ^0.3.1

#  Share us Page
#  share_plus: ^3.0.4'
  flutter_share: ^2.0.0
  in_app_update: ^3.0.0

  # toast
  fluttertoast: ^8.0.8
# networking libraries
  freezed: ^1.1.1
  flutter_bloc: ^8.0.1
  logger: ^1.1.0
  equatable: ^2.0.3
  pretty_dio_logger: ^1.1.1
  dio: ^4.0.4
  retrofit: ^3.0.1+1
  json_annotation: ^4.4.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.9
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  pin_code_fields: ^7.3.0
  #  time picker
  time_picker_sheet: ^0.0.2+1
  date_picker_timeline: ^1.2.3
  razorpay_flutter: ^1.3.0
  cloud_firestore: ^3.1.10

  #vidoplayer
  video_player: ^2.3.0
  chewie: ^1.3.1
  youtube_player_flutter: ^8.0.0

  #location
  geolocator: ^8.2.0
#  geocoder: ^0.2.1

  jitsi_meet: ^4.0.0

  file_picker: ^4.5.1

  url_launcher: ^6.0.20
  flutterfire_ui: ^0.4.0
  firebase_messaging: ^11.4.2
  firebase_analytics: ^9.1.10
  sqflite:
  path:
dev_dependencies:
  flutter_launcher_icons: "^0.9.2"

  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # networking
  build_runner: ^2.1.7
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4


flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/pic_app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/primary/
    - assets/icons/single/
